### ISSUE TITLE
cvecache segfaults on 32 bit architectures

### ISSUE THREAD

**Issue by davide125** [facebookincubator/nvdtools#167]
While attempting to package nvdtools for Fedora, I've noticed the test suite reliably segfaults on 32bit architectures (notably, i686 and armv7hl). You can see the build attempts and logs at https://koji.fedoraproject.org/koji/taskinfo?taskID=58488501

Specifically, looking at the i686 log at https://kojipkgs.fedoraproject.org//work/tasks/8539/58488539/build.log the failure is
```
github.com/facebookincubator/nvdtools/cmd/cpe2cve
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x565ba5ac]
goroutine 23 [running]:
runtime/internal/atomic.Xadd64(0x585c002c, 0x1, 0x0, 0x56741620, 0x5860e158)
	/usr/lib/golang/src/runtime/internal/atomic/asm_386.s:105 +0xc
github.com/facebookincubator/nvdtools/cvefeed.(*Cache).Get(0x585c0000, 0x58602030, 0x2, 0x2, 0x1, 0x58616190, 0x4c)
	/builddir/build/BUILD/nvdtools-0.1.4/_build/src/github.com/facebookincubator/nvdtools/cvefeed/cvecache.go:136 +0x3b
github.com/facebookincubator/nvdtools/cmd/cpe2cve.processAll(0x58600240, 0x58600280, 0x585c20e0, 0x4, 0x6, 0x7, 0x0, 0x0, 0x0, 0x0, ...)
	/builddir/build/BUILD/nvdtools-0.1.4/_build/src/github.com/facebookincubator/nvdtools/cmd/cpe2cve/cpe2cve.go:73 +0xccc
github.com/facebookincubator/nvdtools/cmd/cpe2cve.processInput.func1(0x58600240, 0x58600280, 0x585c20e0, 0x4, 0x6, 0x7, 0x0, 0x0, 0x0, 0x0, ...)
	/builddir/build/BUILD/nvdtools-0.1.4/_build/src/github.com/facebookincubator/nvdtools/cmd/cpe2cve/cpe2cve.go:139 +0x60
created by github.com/facebookincubator/nvdtools/cmd/cpe2cve.processInput
	/builddir/build/BUILD/nvdtools-0.1.4/_build/src/github.com/facebookincubator/nvdtools/cmd/cpe2cve/cpe2cve.go:138 +0x27f
exit status 2
FAIL	github.com/facebookincubator/nvdtools/cmd/cpe2cve	0.009s
```
which points to the `atomic.AddInt64` at https://github.com/facebookincubator/nvdtools/blob/master/cvefeed/cvecache.go#L136

**Comment by davide125** [comment]
You can find a copy of the source RPM and specfile being used in https://bugzilla.redhat.com/show_bug.cgi?id=1912528 in case it helps with the repro.

**Comment by davide125** [comment]
Thanks for the fix! Unfortunately it looks like something else is amiss here. If I apply that patch I don't get the segfault anymore, but the test still fails:
```
      testing: github.com/facebookincubator/nvdtools
github.com/facebookincubator/nvdtools/cmd/cpe2cve
PASS
ok  	github.com/facebookincubator/nvdtools/cmd/cpe2cve	0.008s
github.com/facebookincubator/nvdtools/cmd/csv2cpe
PASS
ok  	github.com/facebookincubator/nvdtools/cmd/csv2cpe	0.005s
github.com/facebookincubator/nvdtools/cmd/redhat_filter
PASS
ok  	github.com/facebookincubator/nvdtools/cmd/redhat_filter	0.005s
github.com/facebookincubator/nvdtools/cmd/rpm2cpe
PASS
ok  	github.com/facebookincubator/nvdtools/cmd/rpm2cpe	0.004s
github.com/facebookincubator/nvdtools/cmd/wfnconvert
PASS
ok  	github.com/facebookincubator/nvdtools/cmd/wfnconvert	0.005s
github.com/facebookincubator/nvdtools/cpedict
PASS
ok  	github.com/facebookincubator/nvdtools/cpedict	0.006s
github.com/facebookincubator/nvdtools/cvefeed
--- FAIL: TestCacheEviction (0.00s)
    eviction_test.go:64: concurrent run: cache size 1758/2048; 2 records cached
    eviction_test.go:91: sequential run #1: more than 1 record cached (2)
    eviction_test.go:93: sequential run #1: cache size 2046/2048; 2 records cached
    eviction_test.go:122: sequentual run #2: cache size 1704/2048; 8 records cached
FAIL
exit status 1
FAIL	github.com/facebookincubator/nvdtools/cvefeed	0.022s
```
Full build output is at https://kojipkgs.fedoraproject.org//work/tasks/6747/58936747/build.log for i686, https://koji.fedoraproject.org/koji/taskinfo?taskID=58936690 is the build task with all platforms.
